on:
  push:
    branches:
      - main

jobs:
  deploy-gcp-function:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authentication on Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'

    - id: 'deploy'
      name: 'Creation of Google cloud function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: '${{ secrets.GCP_FUNCTION_NAME }}'
        runtime: 'python312'
        entry_point: 'telegram_bot_message_handler'
        region: 'europe-central2'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        timeout: '30'
        max_instances: '2'
        https_trigger_security_level: 'secure_always'
        secret_environment_variables: |-
          TELEGRAM_BOT_TOKEN=projects/212766406803/secrets/TELEGRAM_BOT_TOKEN

    - id: 'webhook-telegram-bot'
      run: 'curl --request POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook?url=${{ steps.deploy.outputs.url }}'
