on:
  push:
    branches:
      - main

jobs:
  deploy-gcp-function:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authentication on Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_DEPLOY_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'telegram-bot-message-handler'
        runtime: 'python312'
        entry_point: 'telegram_bot_message_handler'
        region: 'europe-central2'
        project_id: 'man-party-bot'
        timeout: '30'
        max_instances: '2'
        https_trigger_security_level: 'secure_always'
        secret_environment_variables: |-
          TELEGRAM_BOT_TOKEN=projects/212766406803/secrets/TELEGRAM_BOT_TOKEN
